kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "database.fullname" . }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /mnt/data
