apiVersion: v2
name: guestbook
description: A Helm chart for Kubernetes
type: application
version: 2.6.0
appVersion: 2.0.0
dependencies:
    - name: backend
      version: 1.0.0
      repository: https://64791d457585a66a3b3b9149e58fdbb7574f8929@raw.githubusercontent.com/bassambst/helm-repo-private/master
    - name: frontend
      version: 2.0.0
      repository: https://64791d457585a66a3b3b9149e58fdbb7574f8929@raw.githubusercontent.com/bassambst/helm-repo-private/master
    - name: mongodb
      version: 7.8.8
      repository: https://charts.helm.sh/stable
      condition: mongodb.enabled